name: Regression Suite

on:
  push:
    branches: [ master ]
  pull_request:
    types:    [ labeled ]

jobs:
  buildtests:
    if : ${{ github.event.label.name == 'test' }} || ${{ github.event_name == 'push' }}
    strategy:
      max-parallel: 4
      matrix:
        test: [ gnu, intel ]
        runner:   [ cheyenne ]
    name: Test ${{ matrix.test }} on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true

    - name: Test ${{ matrix.test }}
      run: |
        ./hpc-workflows/.ci/runner.py .ci/wrf_arw_tests.json ${{ matrix.test }} -d ..

  removelabel:
    if : ${{ !cancelled() && github.event.label.name == 'test' }}
    name: Remove 'test' label
    needs: buildtests
    - name : Remove 'test' label
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        curl \
          -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: token ${{ github.token }}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/test
  