name: Regression Suite
run-name : Run ${{ inputs.event_name == 'push' && 'CI' || inputs.event_label }} (${{ inputs.event_name }})

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Actual ref to use
        required: false
        default: null
        type: string
      sha:
        description: Actual sha to use
        required: false
        default: null
        type: string
      event_name:
        description: Event name that triggered this dispatch
        required: false
        default: push
        type: string
      event_number:
        description: Event number that triggered this dispatch
        required: false
        default: 0
        type: string
      event_label:
        description: Event label that triggered this dispatch
        required: true
        default: all-tests
        type: choice
        options:
          - all-tests
          - compile-tests


# https://docs.github.com/en/actions/sharing-automations/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
# Also https://stackoverflow.com/a/74959635
# TL;DR - For public repositories the safest approach will be to use the default read permissions, but at the cost
# of not being able to modify the labels. That will need to be a separate [trusted] workflow that runs from the base repo
# permissions :
#   contents : read
#   pull-requests : write
  
# Write our tests out this way for easier legibility
# testsSet    :
#   - key : value
#     key : value
#     tests :
#       - value
#       - value
#   - < next test >
# https://stackoverflow.com/a/68940067
jobs:
  buildcmake:
    if : ${{ contains( fromJson('["compile-tests","all-tests"]'), inputs.event_label ) || inputs.event_name == 'push' }}
    name : Test ${{ matrix.workflow.name }} on ${{ matrix.workflow.host }}
    runs-on: ${{ matrix.workflow.host }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        workflow  :
          - host : derecho
            name : "Make Compilation Tests"
            id   : make-tests
            label: buildcmake
            args : -vr='{"cpus":128,"timelimit":"00:10:00"}'
            patch : 
              - priority : -99
              - hosts :
                - '[.*derecho.*]' :
                  - account : NMMM0012
                  - queue   : main
            actions :
              - build_cmake_arw_em_real_gnu_release_dm
              - build_cmake_arw_em_real_gnu_debug_dm
    # I am leaving this here for posterity if this is to be replicated in private repositories for testing
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      # Don't use gh checks as they are woefully underdeveloped as a feature leading
      # to confusing UI and misplaced metrics
      # https://github.com/orgs/community/discussions/24616
      - name: Set pending status
        id: check_run_start
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner:      context.repo.owner,
              repo:       context.repo.repo,
              sha:        '${{ inputs.event_name == 'push' && github.sha || inputs.sha }}',
              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description: '${{ inputs.name }}',
              context:     '${{ inputs.host }}/${{ inputs.id }}',
              state:      'pending'
            })

      - uses: ./.github/actions/sane_workflows
        name: ${{ inputs.name }}
        with:
          # Everything below this should remain the same and comes from the workflow matrix
          id       : ${{ matrix.workflow.id }}
          host     : ${{ matrix.workflow.host }}
          actions  : ${{ toJson( matrix.workflow.actions ) }}
          mkdirs   : ${{ matrix.workflow.mkdirs }}
          args     : ${{ matrix.workflow.args }}
          patch    : '${{ toJson( matrix.workflow.patch ) }}'

      - name: Set completed status
        if: ${{ always() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner:        context.repo.owner,
              repo:         context.repo.repo,
              sha:          '${{ inputs.event_name == 'push' && github.sha || inputs.sha }}',
              target_url:   '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}',
              description:  '${{ matrix.workflow.name }}',
              context:      '${{ matrix.workflow.host }}/${{ matrix.workflow.id }}',
              state:        '${{ job.status == 'success' && 'success' || 'failure' }}'
            })

      - name : Remove '${{ matrix.workflow.label }}' label
        if : ${{ !cancelled() && inputs.event_label == matrix.workflow.label }}
        env:
          PR_NUMBER: ${{ inputs.event_number }}
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ github.token }}' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/${{ matrix.workflow.label }}

  # In the event that 'all-tests' is used, this final job will be the one to remove
  # the label from the PR
  removeAllLabel :
    if : ${{ !cancelled() && inputs.event_label == 'all-tests' }}
    name : Remove 'all-tests' label
    runs-on: ubuntu-latest
    needs : [ buildcmake ] # Put tests here to make this wait for the tests to complete
    permissions:
      pull-requests: write
    steps: 
      - name : Remove '${{ inputs.event_label }}' label
        env:
          PR_NUMBER: ${{ inputs.event_number }}
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'Authorization: token ${{ github.token }}' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/labels/${{ inputs.event_label }}
